### ISSUE TITLE
Allow use of Rails5

### ISSUE THREAD

**Issue by cflipse** [rom-rb/rom-model#4]
I've loosened up the dependencies on master, so HEAD can be checked against rails5.

Tests locally pass without warning, but the tests in rom-rb/rom-rails produce a boatload of warnings around `Parameter#to_hash` which evidently is no longer considered "safe"  ...

**Comment by solnic** [comment]
What's `Parameter#to_hash`?

**Comment by cflipse** [comment]
In rails 4.x, `Parameter < ActiveSupport::HashWithIndifferentAccess` and so, `to_hash` basically just returned self.

In 5.x, it's it's own class, and `to_hash` throws a warning while returning a new hash.

I _think_ it forwards to `to_unsafe_hash` which basically bypasses all of the strong parameter guards.

The .. more relevant tracker is over here:  https://github.com/rom-rb/rom-rails/pull/62

**Comment by cflipse** [comment]
Travis is failing; it seems that Rails5 has dropped support for ruby 2.1 and rbx2.

https://travis-ci.org/rom-rb/rom-model/builds/147879706

Given that this gem only makes sense in the context of rails, I'm gonna update the travis configs for that.

**Comment by cflipse** [comment]
completed in v0.4.0
